✨  Nhj consensusmerge docker
d3b-center/bixtools pull request #100
Opened 2021-03-10 16:02 UTC by NHJohnson

## Description

This is a Dockerfile and CircleCI config for the consensus_merge script for the somatic consensus workflow.  

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [X] Dockerfile builds on EC2 instance
- [X] Script runs with `--help` in container

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2021-03-10 19:13 UTC, migbro commented on consensus-merge/1.0.0/Dockerfile
> +RUN curl -sL https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -o /tmp/miniconda.sh && \
Please consolidate, as much as possible (in this case, you can do all) the `RUN` commands as a single one, and string with `&&`. Doing so cuts the image size, in this case in half, as each `RUN` call adds a layer to the docker image and sometimes significantly inflate the size.

2021-03-12 01:08 UTC, migbro requested changes
This may sound crazy, but please be even more aggressive with consolidation. All of the ENVs can be clustered together, and then merge `RUN apt update -y && apt install -y curl` and 

```
RUN curl -sL https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -o /tmp/miniconda.sh && \
    sh /tmp/miniconda.sh -bfp /usr
```
into the other `RUN` cmd. It'll lop off like another 200MB.

2021-03-12 15:40 UTC, dmiller15 approved these changes

2021-03-12 16:19 UTC, migbro approved these changes
Awesome! In case you were curious, build size after each iteration:
1. 1.55 GB
2. 954MB
3. 705MB

2021-03-12 16:29 UTC, NHJohnson commented
I was wondering, thanks!

2021-03-12 16:32 UTC, merged