✨ cnvnator init
d3b-center/bixtools pull request #105
Opened 2021-04-08 15:09 UTC by dmiller15

## Description

Adds Docker for CNVnator 0.4.1. Pretty much just copied the Dockerfile they provide in their [repo](https://github.com/abyzovlab/CNVnator/blob/master/Dockerfile) but changed how the source code is pulled in. I chose the most recent release but the Makefile proved to be problematic. I noticed they had patched that after the 0.4.1 release so I pull the most recent commit for that file.

Part of https://github.com/d3b-center/bixu-tracker/issues/788

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Builds locally and used to run all of my tests

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

2021-04-08 19:16 UTC, mark-welsh approved these changes
looks good, built successfully 👍

2021-04-08 19:20 UTC, sickler-alex requested changes

2021-04-08 19:20 UTC, sickler-alex commented on cnvnator/v0.4.1/Dockerfile
> +
Add the maintainer label.

2021-04-08 19:27 UTC, dmiller15 commented on cnvnator/v0.4.1/Dockerfile
> +
Done

2021-04-09 12:28 UTC, sickler-alex approved these changes

2021-04-09 13:57 UTC, merged