Feature/annofuse:v0.91.0
d3b-center/bixtools pull request #137
Opened 2022-09-27 10:25 UTC by sakshamphul

## Description

This PR brings in a docker for latest version of annofuse.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This was test locally by building the docker image and running annofuse within the container. It takes close to 15 mins to build this images

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have committed any related changes to the PR

2022-09-29 18:28 UTC, luederm approved these changes
Looks good although I don't know enough to review the circleci config

2022-09-29 21:01 UTC, migbro requested changes
Everything seems good except annoFusePerSample script. Sine annofuse ought to already have been built, it should only try to install annofuse if for some reason it is being run outside the docker env

2022-09-30 04:15 UTC, sakshamphul commented on annoFuse/0.91.0/annoFusePerSample.R
> +install.packages("/opt/formatFusionCalls/annoFuse_0.90.0.tar.gz",repos = NULL)
Nice catch! I have update the code

2022-10-06 19:14 UTC, migbro approved these changes
Thanks for the fix!

2022-10-10 15:01 UTC, merged