As add zumis
d3b-center/bixtools pull request #79
Opened 2020-10-05 15:26 UTC by sickler-alex

Created docker for zUMIs 2.9.4.

2020-10-06 19:56 UTC, migbro requested changes
Small request, but looks good overall. Perhaps @dmiller15 can comment on the coonfig file format

2020-10-06 19:56 UTC, migbro commented on zumis/2.9.4/Dockerfile
> +
Perhaps add a comment in the docker file and in the eventual readme to ignore the `./zUMIs.sh: line 7: curl: command not found` warning, as you have explained that it has the undesired effect of trying to upgrade the repo

2020-10-08 20:35 UTC, migbro approved these changes
Looks good, thanks!

2020-10-08 21:36 UTC, dmiller15 approved these changes
Looks good. Although I wonder why those annofuse config statements moved around.

2020-10-09 12:36 UTC, merged